### ISSUE TITLE
How to run this project on physical device?

### ISSUE THREAD

**Issue by aahevolution** [fromtexas/react-native-news-app#3]
Description of the Issue and Steps to Reproduce:

Please include the values of all variables used.

Environment:

Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4

Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.

**Comment by fromtexas** [comment]
do u need bundle? or u asking about dev mode?

**Comment by aahevolution** [comment]
Basically I need step to step procedure of running your react-native project on my physical device?

**Comment by fromtexas** [comment]
> Installing
> Clone Repository
> cd react-native-news-app
> npm i
> npm start

did you tried this?

**Comment by aahevolution** [comment]
yes,It is not working on my physical device

**Comment by aahevolution** [comment]
I want to run your project on my physical device

**Comment by fromtexas** [comment]
do u have Expo on your physical device?

**Comment by aahevolution** [comment]
no
can we run this project without expo?

**Comment by fromtexas** [comment]
u can read [here](https://facebook.github.io/react-native/docs/running-on-device) how to run RN app on your device after Expo eject

**Comment by aahevolution** [comment]
So,I have run your project on my physical device using expo.

**Comment by aahevolution** [comment]
Now I want run it without using expo?
Error-->> 
Android project not found. Maybe run react-native android first?

**Comment by aahevolution** [comment]
Where you have done the linking part?

**Comment by aahevolution** [comment]
when I put the category  and the country part It shows the news
so 
in which folder you have put the API part

**Comment by fromtexas** [comment]
https://newsapi.org/ <--

**Comment by aahevolution** [comment]
Can you help me with running  this project without using expo on physical device?

**Comment by fromtexas** [comment]
Later I'll try to write a guide how to run this project on physical device without using expo. But currently I don't have enough free time to do it.

**Comment by aahevolution** [comment]
Cannot find module 'expo/tools/LogReporter
can you please give some solution about this??

**Comment by aahevolution** [comment]
I am trying to run your project  with expo once more but it is not running

These 2 errors are coming
Can you please help me??
Cannot find module 'expo/tools/LogReporter'
Set EXPO_DEBUG=true in your env to view the stack trace.

how do i solve these two errors??

**Comment by fromtexas** [comment]
https://github.com/expo/expo-cli/issues/247

**Comment by aahevolution** [comment]
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2019-07-19T19_52_16_488Z-debug.log


how do i solve these two errors??

**Comment by aahevolution** [comment]
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\xxx\AppData\Roaming\npm-cache_logs\2019-07-19T19_52_16_488Z-debug.log

how do i solve these two errors??
